---
sidebar: sidebar 
permalink: concept_acquisition_unit_requirements.html 
summary: 作為採購單位的伺服器或 VM 必須符合最低需求。 
keywords: AU, acquisition unit, requirements, sizing 
---
= 採購單位需求
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您必須安裝擷取單元（AU）、才能從基礎架構資料收集器（儲存設備、VM、連接埠、EC2等）取得資訊。安裝擷取單元之前、您應確保環境符合作業系統、CPU、記憶體及磁碟空間需求。



== 需求

|===


| 元件 | Linux需求 | Windows需求 


| 作業系統 | 執行下列其中一項授權版本的電腦：

* CentOS （ 64 位元）： 7.2 至 7.9 、 8.1 至 8.4 、 Stream 8 、 Stream 9
* AlmaLinux 9.3 和 9.4
* Debian （ 64 位元）： 9 和 10
* openSUSE Leap 15.1 到 15.5
* Oracle Enterprise Linux （ 64 位元）： 7.5 至 7.9 、 8.1 至 8.8
* Red Hat Enterprise Linux （ 64 位元）： 7.2 至 7.9 、 8.1 至 8.10 、 9.1 至 9.4
* Rocky 9.0 至 9.4
* SUSE Enterprise Linux Server 15 、 15 SP2 至 15 SP5
* Ubuntu 伺服器： 18.04 、 20.04 、 22.04 LTS
* 上述平台上的 SELinux

此電腦不應執行其他應用程式層級的軟體。建議使用專屬伺服器。

如果您使用 SELinux 執行、建議您在擷取單元系統上執行下列命令：

 Sudo sanage fcontext -a -t usr_t "/opt/NetApp/cloudimses//.*)"
 Sudo restorecon -R /opt/NetApp/cloudsights | 執行下列其中一種授權版本的電腦： * Microsoft Windows 10 64位元* Microsoft Windows Server 2012 * Microsoft Windows Server 2012 R2 * Microsoft Windows Server 2016 * Microsoft Windows Server 2019 * Microsoft Windows Server 2022 * Microsoft Windows 11此電腦不應執行其他應用程式層級軟體。建議使用專屬伺服器。 


| CPU | 2個CPU核心 | 相同 


| 記憶體 | 8 GB RAM | 相同 


| 可用磁碟空間 | 50 GB （建議使用 100 GB ）
對於 Linux 、應以下列方式分配磁碟空間：
/opt/NetApp 10 GB （大型環境為 20 GB ）
/var/log/NetApp 40 GB （大型環境為 80 GB ）
/tmp 在安裝期間至少有 1 GB 可用空間 | 50 GB 


| 網路 | 需要 100 Mbps/1 Gbps 乙太網路連線、靜態 IP 位址、以及連接埠 80 或 443 的連線能力、從擷取單元連線至 * .cloudinsights.netapp.com 或您的 Cloud Insights 環境（例如： https ： <environment_id>.c01.cloudinsights.netapp.com ）。如需擷取單元與每個資料收集器之間的需求、請參閱的說明 link:data_collector_list.html["資料收集器"]。

如果您的組織需要使用Proxy才能存取網際網路、您可能需要瞭解組織的Proxy行為、並尋求Cloud Insights 某些例外情況、才能讓無法運作。例如、貴組織是否預設會封鎖存取、而且例外情況下只允許存取特定網站/網域？如果是、您需要將下列網域新增至例外清單：

* .cloudinsights.netapp.com

如需詳細資訊、請參閱關於代理 link:task_troubleshooting_linux_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls["這裡（ Linux ）"] 或 link:task_troubleshooting_windows_acquisition_unit_problems.html#considerations-about-proxies-and-firewalls["這裡（ Windows ）"]。 | 相同 


| 權限 | 擷取單元伺服器上的Sudo權限。/tmp必須以執行功能掛載。 | 取得單位伺服器的系統管理員權限 


| 掃毒 |  | 安裝期間、您必須完全停用所有的掃毒程式。安裝之後、擷取單元軟體所使用的路徑必須排除在掃毒範圍之外。 
|===


== 其他建議

* 為確保稽核與資料報告的準確性、強烈建議您使用*網路時間傳輸協定（NTP）*或*簡易網路時間傳輸協定（SNTP）*來同步擷取裝置機器上的時間。




== 關於規模調整

您可以開始使用Cloud Insights 僅有8GB記憶體和50GB磁碟空間的支援中心、不過對於較大型的環境、您應該自問下列問題：

您是否期望：

* 在ONTAP 這個擷取單元上探索超過2500部虛擬機器或10部大型（> 2個節點）的VMware叢集、Symmetrix或HDS/HPE VSP/XP陣列？
* 在此擷取單元上部署總共75個以上的資料收集器？


對於上述每個「是」答案、建議您在AU中新增8 GB記憶體和50 GB磁碟空間。舉例來說、如果您對這兩個項目都回答「是」、就應該部署一個24GB記憶體系統、其中有150GB或更多的磁碟空間。在Linux上、要新增至記錄位置的磁碟空間。

如需其他規模調整問題、請聯絡NetApp支援部門。



== 聯邦版的額外要求

* 在 Cloud Insights 聯邦版叢集中安裝採購單元時、基礎作業系統必須具備良好的 Entropy 來源。在 Linux 系統上、這通常是透過安裝 _rng-tools_ 或使用硬體隨機號碼產生（ RNG ）來完成。客戶有責任確保擷取單元機器符合此要求。

