---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: 支援Telegraf做為其代理程式、可在Kubernetes上收集整合資料。Cloud Insights 
---
= 安裝或升級 NetApp Kubernetes 監控操作員之前
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
在安裝或升級之前、請先閱讀此資訊 link:task_config_telegraf_agent_k8s.html["Kubernetes 監控營運者"]。



=== 先決條件：

|===
| 元件 | 需求 


| Kubernetes版本 | Kubernetes v1.20 及更高版本。 


| Kubernetes 配送 | AWS Elastic Kubernetes 服務（ EKS ）
Azure Kubernetes服務（KS）
Google Kubernetes Engine（GKE）
Red Hat OpenShift
Rancher Kubernetes引擎（RKE）
VMware Tanzu 


| Linux 作業系統 | Cloud Insights 不支援以 Arm64 架構執行的節點。

網路監控：必須執行 Linux 核心版本 4.18.0 或更新版本。不支援光子作業系統。 


| 標籤 | 支援監控執行Linux的Kubernetes節點、方法是指定Kubernetes節點選取器、在這些平台上尋找下列Kubernetes標籤：Cloud Insights

Kubernetes v1.20 及更高版本： Kubernetes.IO/OS = Linux
Rancher + Cattle .IO 做為協調 / Kubernetes 平台： Cattle .IO/OS = Linux 


| 命令 | curl 和 kubectl 命令必須可用；若要獲得最佳結果、請將這些命令新增至路徑。 


| 連線能力 | Kubectl CLI 已設定為與目標 K8s 叢集通訊、並可與 Cloud Insights 環境進行網際網路連線。

如果您在安裝期間位於 Proxy 後方、請遵循中的指示 link:/task_config_telegraf_agent_k8s.html#configuring-proxy-support["設定Proxy支援"] 操作員安裝部分。

若要準確地進行稽核和資料報告、請使用網路時間傳輸協定（ NTP ）或簡易網路時間傳輸協定（ SNTP ）來同步代理機器上的時間。 


| 其他 | 如果您是在 OpenShift 4.6 或更新版本上執行、則必須遵循連結： task_config_telegraf_agent_k8s.html#openshift-instructions [OpenShift Instructions 、同時確保符合這些先決條件。 


| API Token | 如果您要重新部署操作員（亦即您正在更新或取代它）、則不需要建立新的 API 權杖；您可以重新使用先前的權杖。 
|===


=== 設定操作員

在較新版本的運算子中、最常修改的設定可在 _AgentConfiguration_ 自訂資源中進行設定。您可以編輯 _operer-config.yaml_ 檔案、在部署運算子之前編輯此資源。此檔案包含一些設定的註解範例。請參閱清單 link:telegraf_agent_k8s_config_options.html["可用的設定"] 適用於最新版的運算子。

您也可以使用下列命令在部署運算子之後編輯此資源：

 kubectl -n netapp-monitoring edit AgentConfiguration
若要判斷您部署的營運者版本是否支援 AgentConfiguration 、請執行下列命令：

 kubectl get crd agentconfigurations.monitoring.netapp.com
如果您看到「錯誤來自伺服器（ NotFound ）」訊息、則必須先升級您的營運商、才能使用 AgentConfiguration 。



=== 公差和污染

_NetApp-CI-telegraf-DS_ 、 _NetApp-CI-Fluent-bit-DS_ 和 _NetApp-CI-net-觀察者 -L4-DS_ 示範必須在叢集中的每個節點上排程一個 Pod 、以便正確收集所有節點上的資料。已將操作員配置爲允許某些已知的 * 污點 * 。如果在節點上配置了任何自定義污點，從而阻止 Pod 在每個節點上運行，則可以爲這些污點創建一個 *公差 * link:telegraf_agent_k8s_config_options.html["在 _AgentConfiguration_ 中"]。如果您已將自訂污點套用至叢集中的所有節點、您也必須在操作員部署中新增必要的容錯功能、以便排程及執行操作員 Pod 。

深入瞭解 Kubernetes link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["污染與容許"]。

返回 link:task_config_telegraf_agent_k8s.html["* NetApp Kubernetes 監控操作員安裝 * 頁面"]
