---
sidebar: sidebar 
permalink: security_admin_tool.html 
summary: 整個發行生命週期中、均遵循安全最佳實務做法。Cloud Insights 
keywords: security, risk, protection 
---
= 安全性管理工具
:allow-uri-read: 


[role="lead"]
CI具備安全功能、可讓Insight環境以增強的安全性運作。這些功能包括加密、密碼雜湊、以及變更加密和解密密碼的內部使用者密碼和金鑰配對的能力。

為了保護敏感資料、NetApp建議您在安裝或升級後變更預設金鑰和擷取使用者密碼。

資料來源加密密碼儲存在Cloud Insights 效益管理系統中、當使用者在資料收集器組態頁面中輸入密碼時、會使用公開金鑰來加密密碼。不具備解密資料收集器密碼所需的私密金鑰；只有擷取單位擁有解密資料收集器密碼所需的資料收集器私密金鑰Cloud Insights 。



== 升級與安裝考量

如果Insight系統包含非預設的安全性組態（亦即您有重新輸入的密碼）、則必須備份安全性組態。安裝新軟體、或在某些情況下升級軟體、會將系統還原為預設的安全組態。當系統恢復為預設組態時、您必須還原非預設組態、系統才能正常運作。



== 管理採購單位的安全性

安全性管理工具可讓您管理Cloud Insights 適用於此功能的安全性選項、並可在採購單位系統上執行。安全管理包括管理金鑰和密碼、儲存及還原您建立的安全組態、或將組態還原為預設設定。



== 開始之前

您必須擁有AU系統的管理員權限、才能執行安全組態工作。

關於此工作、安全管理工具可在下列任一位置的採購單位系統上找到：

* * Windows - C：\Program Files\SANSANSANSANW\securityadmin\bin\securityadmin.bat
* * Linux -/BIN/oci-securityadmin.sh


.步驟
* *以互動模式（-I）啟動安全管理工具。
+
畫面會顯示下列選項：

* 備份
+
建立包含所有密碼和金鑰的資料保險箱備份壓縮檔、並將檔案放置在使用者指定的位置、或是下列預設位置：

+
....
Windows - C:\Program Files\SANscreen\backup\vault
Linux - /var/log/netapp/oci/backup/vault
....
* 還原
+
還原所建立之資料保存庫的壓縮備份。還原之後、所有密碼和金鑰都會還原為建立備份時的現有值。

+
還原可用於同步多個伺服器上的密碼和金鑰、例如：-變更AU上的加密金鑰-建立資料庫備份-將資料庫備份還原至每個Aus

* 變更加密金鑰
+
變更用於加密或解密裝置密碼的AU加密金鑰。

+
變更加密金鑰時、您應該備份新的安全性組態、以便在升級或安裝之後還原。

* 更新密碼
+
變更「擷取」使用者帳戶的密碼。

+
變更密碼時、您應該備份新的安全組態、以便在必要時還原。

* 重設為預設值
+
將擷取使用者密碼和擷取使用者加密金鑰重設為預設值、預設值為安裝期間提供的值。

* 結束
+
結束安全性管理工具。



選擇您要設定的選項、然後依照提示進行。
