---
sidebar: sidebar 
permalink: task_troubleshooting_general_problems.html 
summary: 一般Cloud Insights 故障排除秘訣。 
keywords: troubleshooting, problems, browser, login, log in, accessing, access to, Trident, qtree, quota 
---
= 疑難排解一般Cloud Insights 的問題
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可在此找到疑難排解Cloud Insights 功能的建議。

另請參閱 link:task_troubleshooting_linux_acquisition_unit_problems.html["疑難排解Linux擷取單元問題"] 和 link:task_troubleshooting_windows_acquisition_unit_problems.html["疑難排解Windows接收單元問題"]。



== 登入問題

|===
| *問題：* | *試用：* 


| 每5分鐘登出一次Cloud Insights | 讓第三方接受必要的NetApp和auth0 Cookie。

範例：
在 Chrome 的瀏覽器 URL 中輸入「 chrome://settings/Cookie 」。

選取「允許所有Cookie」選項。
*或*
選取「封鎖協力廠商 Cookie 」、並新增 [\*.]auth0.com 和 [*.]netapp.com 的例外。

附註：建立例外狀況時、請務必選取「在此網站上包含第三方Cookie」選項。 


| 我有 BlueXP 帳戶、但無法登入 BlueXP 。 | 從開啟問題單 https://mysupport.netapp.com/site/help[]。選擇類別「 blueXP.netapp.com > 帳戶 / 登入問題」或「 bluexp.netapp.com > 聯盟問題」。  這些是專為 BlueXP 問題所設計。
如Cloud Insights 需所有其他的支援問題、請聯絡 link:concept_requesting_support.html["NetApp支援"]。 


| 我受邀參加Cloud Insights 這個項目、但我收到「未經授權」的訊息。 | 確認您已註冊 BlueXP 帳戶、或貴組織使用 SSO 登入 BlueXP 。

確認 BlueXP 設定檔電子郵件地址與 Cloud Insights 歡迎電子郵件中顯示的電子郵件地址相符。如果電子郵件不符、請以正確的電子郵件地址申請新的邀請函。 


| 我已從 BlueXP 登出、並自動從 Cloud Insights 登出。 | 跨 NetApp 雲端服務的單一登入（ SSO ）會登出所有 Cloud Insights 工作階段。如果您有多Cloud Insights 個支援帳戶的存取權限、請從任何一個帳戶登出、登出所有使用中的工作階段。重新登入以存取您的帳戶。 


| 我在數天後自動登出。 | NetApp Cloud 帳戶每隔幾天就需要重新驗證（目前的 BlueXP 設定是 7 天）。重新登入以存取您的帳戶。 


| 我收到錯誤訊息「不再授權登入」。 | 請聯絡您的帳戶管理員、確認是否有權限存取Cloud Insights 功能。
確認 BlueXP 設定檔電子郵件地址與 Cloud Insights 歡迎電子郵件中顯示的電子郵件地址相符 


| 其他登入錯誤 | 請在Chrome中嘗試無痕式模式、或清除瀏覽器記錄、Cookie和快取。嘗試使用不同的瀏覽器設定檔（例如 Chrome -新增人員）。 
|===


== 其他問題

|===


| * 問題： * | * 答案： * 


| 我的 Qtree 硬式配額在查詢中顯示正確、但我的軟式配額顯示為磁碟區的總容量。答對了嗎？ | 只有硬配額（手動設定或透過 Trident 設定）會顯示為設定配額；如果未指定硬配額、則 Qtree 容量會是內部 Volume 容量。 


| 我在同一個 Qtree 中手動設定了軟配額和硬配額、但顯示的總容量是硬配額、對嗎？ | 是、如果指定硬配額、則會顯示為總容量。 


| 輸入 Cognos 報告排程時間時、有時我會在排程時間加上額外的「 m 」。例如、如果我輸入時間為「 02 ： 15 PM 」、可能會新增額外的字元：「 02 ： 15 PMM 」（或 PMM ）。當我按一下外部時、它會變更為「上午 2 ： 15 」。

我可以儲存報告、但當我重新開啟儲存的報告時、排程時間會顯示為 AM （即晨間）、無論我是在排程時間中輸入 AM 或 PM 。 | 請重新輸入排程時間、小心不要輸入完整的「 AM 」或「 PM 」字元、只要在「 AM 」或「 P 」輸入「 A 」即可。如果您沒有看到額外的字元、排程時間將會正確設定。 
|===


== 資源

如需其他疑難排解秘訣、請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights["NetApp知識庫"] （需要支援登入）。

如需其他支援資訊、請參閱Cloud Insights 《支援資訊 link:concept_requesting_support.html["支援"] 頁面。

如果您使用Cloud Insights 的是動態的支援功能、您可以使用下列支援選項：

link:https://www.netapp.com/us/contact-us/support.aspx["電話"]
link:https://mysupport.netapp.com/site/cases/mine/create?serialNumber=95001014387268156333["支援服務單"]

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html["支援文件Cloud Insights"]。
