---
sidebar: sidebar 
permalink: task_dc_na_ontap_rest.html 
keywords: data collector, ontap, ontap, CDOT, REST 
summary: ONTAP REST Data Collector 
---
= NetApp ONTAP REST 資料收集器
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此資料收集器會使用 REST API 呼叫、從執行 ONTAP 9.14.1 及更高版本的儲存系統擷取庫存、 EMS 記錄和效能資料。對於舊版 ONTAP 系統、請使用 ZAPI 型的「 NetApp ONTAP 資料管理軟體」收集器類型。



== 術語

Cloud Insights 會從 ONTAP 資料收集器取得庫存、記錄和效能資料。對於所取得的每種資產類型、都會顯示該資產最常用的術語。檢視或疑難排解此資料收集器時、請謹記下列術語：

[cols="2*"]
|===
| 廠商/模型術語 | 詞彙Cloud Insights 


| 磁碟 | 磁碟 


| RAID群組 | 磁碟群組 


| 叢集 | 儲存設備 


| 節點 | 儲存節點 


| Aggregate | 儲存資源池 


| LUN | Volume 


| Volume | 內部Volume 
|===


== 資料管理術語ONTAP

下列詞彙適用於ONTAP 您在《支援資料管理》儲存資產登陸頁面上可能找到的物件或參考資料。其中許多術語也適用於其他資料收集器。



=== 儲存設備

* 模型–此叢集內唯一、獨立節點模型名稱的以逗號分隔的清單。如果叢集內的所有節點都是相同的模型類型、則只會顯示一個模型名稱。
* 廠商–如果您要設定新的資料來源、您會看到相同的廠商名稱。
* 序號–陣列 UUID
* IP–通常是在資料來源中設定的IP或主機名稱。
* 微碼版本–韌體。
* 原始容量：系統中所有實體磁碟的基礎2總和、無論其角色為何。
* 延遲：代表主機面對的工作負載在讀取和寫入過程中所經歷的情況。理想的情況Cloud Insights 是、這個價值是直接來源於此、但這種情況通常並非如此。代替陣列提供此功能、Cloud Insights 往往會執行IOP加權計算、以個別內部磁碟區的統計資料為基礎。
* 處理量：從內部磁碟區集合而來。管理：這可能包含裝置管理介面的超連結。以程式設計的方式、由Cloud Insights 來源資料來源建立、作為庫存報告的一部分。




=== 儲存資源池

* 儲存設備：此資源池所使用的儲存陣列。必填。
* 類型–從列舉的可能性清單清單中選取一個描述性值。最常見的是「Aggregate」或「RAID Group」。
* 節點–如果此儲存陣列的架構使集區屬於特定儲存節點、則其名稱將會顯示在這裡、以超連結的形式連結至其自己的登陸頁面。
* 使用Flash Pool–是/否值–此SATA / SAS型集區是否使用SSD進行快取加速？
* 備援：RAID層級或保護方案。RAID-DP為雙同位元檢查、RAID_tp為三同位元檢查。
* 容量：此處的值是已用邏輯容量、可用容量和邏輯總容量、以及這些容量使用的百分比。
* 過度委派容量：如果使用效率技術、您已將容量或內部Volume容量的總和分配給大於儲存資源池邏輯容量的總和、則此處的百分比值將大於0%。
* Snapshot–已使用的快照容量和總容量、如果您的儲存資源池架構將部分容量專用於專為快照而設計的區段區域。在不支援支援的情況下、支援的部分可能會出現這個問題、而其他的不支援的組態則較少。ONTAP MetroCluster ONTAP
* 使用率–百分比值、顯示此儲存資源池中任何磁碟貢獻容量的最高磁碟使用率百分比。磁碟使用率不一定與陣列效能有密切的關聯、因為磁碟重建、重複資料刪除活動等原因、在缺乏主機驅動的工作負載的情況下、使用率可能會很高。此外、許多陣列的複寫實作可能會提高磁碟使用率、但不會顯示為內部磁碟區或磁碟區工作負載。
* IOPS：所有磁碟的IOPs總和、可為此儲存資源池提供容量。處理量：所有磁碟的總處理量、可為此儲存資源池提供容量。




=== 儲存節點

* 儲存設備：此節點屬於何種儲存陣列。必填。
* HA合作夥伴：在節點將容錯移轉至一個節點、而只有一個節點的平台上、通常會顯示於此處。
* 狀態–節點健全狀況。只有當陣列健全狀況足以由資料來源進行庫存時、才能使用。
* 模型–節點的模型名稱。
* 版本–裝置的版本名稱。
* 序號–節點序號。
* 記憶體：基礎2記憶體（若有）。
* 使用率：ONTAP 在功能方面、這是專屬演算法的控制器壓力索引。每次效能意見調查都會報告0到100%之間的數字、這是WAFL 指較高的VMware磁碟爭用或平均CPU使用率。如果您觀察到持續值> 50%、這表示規模過小–可能是控制器/節點不夠大、或旋轉磁碟不足以吸收寫入工作負載。
* IOPS –直接衍生自節點物件上的 ONTAP REST 通話。
* 延遲–直接衍生自節點物件上的 ONTAP REST 通話。
* 處理量–直接衍生自節點物件上的 ONTAP REST 通話。
* 處理器–CPU數。




== 需求

以下是設定及使用此資料收集器的需求：

* 您必須具有所需存取層級的使用者帳戶存取權。請注意、如果建立新的 REST 使用者 / 角色、則需要管理員權限。
* 帳戶詳細資料包括使用者名稱和密碼。
* 連接埠需求： 443
* 帳戶權限：
+
** 在功能上、 Cloud Insights 正在提出讀取要求、但 Cloud Insights 必須具備一些寫入權限、才能向 ONTAP 陣列註冊。請參閱 <<a-note-about-permissions,權限注意事項>> 以下。






== 組態

[cols="2*"]
|===
| 欄位 | 說明 


| ONTAP 管理 IP 位址 | NetApp叢集的IP位址或完整網域名稱 


| ONTAP REST 使用者名稱 | NetApp叢集的使用者名稱 


| ONTAP REST 密碼 | NetApp叢集的密碼 
|===


== 進階組態

[cols="2*"]
|===
| 欄位 | 說明 


| 庫存輪詢時間間隔（分鐘） | 預設為60分鐘。 


| 效能意見調查時間間隔（秒） | 預設為 60 秒。 


| 進階計數器資料收集 | 選取此選項可在ONTAP 輪詢中包含「功能先進的計數器」資料。預設為啟用。 


| 啟用 EMS 事件收集 | 選取此選項以納入 ONTAP EMS 記錄事件資料。預設為啟用。 


| EMS 輪詢時間間隔（秒） | 預設為 60 秒。 
|===


== ONTAP 電力指標

多種 ONTAP 機型提供 Cloud Insights 的電力指標、可用於監控或警示。下列支援和不支援的機型清單並不完整、但應提供一些指引；一般而言、如果機型與清單上的機型屬於同一個系列、則支援應該相同。

支援的機型：

A200
A220
解答 250
A300
A320
A400
a700
A700s
A800
A900
C190
FAS2240-4.
FAS2552
FAS2650
FAS2720
FAS2750
FAS8200
FAS8300
FAS8700
FAS9000

不支援的機型：

FAS2620
FAS3250
FAS3270
FAS500f
FAS6280
FAS / AFF 8020
FAS / AFF 8040
FAS / AFF 8060
FAS / AFF 8080



== 權限相關注意事項

由於許多 Cloud Insights 的 ONTAP 儀表板都仰賴進階 ONTAP 計數器、因此您應該在資料收集器進階組態區段中保持啟用 * 啟用進階計數器資料收集 * 。

若要在Cloud Insights 叢集層級建立一個用於執行故障的本機帳戶、ONTAP 請使用叢集管理管理員使用者名稱/密碼登入到故障碼、然後在ONTAP 故障碼伺服器上執行下列命令：

. 開始之前、您必須先以ONTAP _Administrator帳戶登入到VMware、然後才能啟用_diagnostic-level命令_。
. 使用下列命令建立角色：


安全登入 REST 角色建立角色 ｛ role name ｝ -API /API -access readonly
安全登入 REST 角色建立角色 ｛ role name ｝ -API /API/cluster / agents -access all

vserver 服務 Web 存取 create -name spi -role ｛ role name ｝ -vserver ｛ name from 上述命令 ｝
安全登入 create -user-or -group-name ｛ userName ｝ -application http -authent驗 證方法密碼 -role ｛ role name ｝

....
 ////
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
 security login role create -role ci_readonly -cmddirname security -access readonly
 security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
 ////
....
. 使用下列命令建立唯讀使用者。執行create命令後、系統會提示您輸入此使用者的密碼。
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


如果使用AD/LDAP帳戶、則命令應該是

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
產生的角色和使用者登入內容如下。實際輸出可能有所不同：

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1   ci_readonly   DEFAULT   read only
cluster1   ci_readonly   security  read only
....
....
cluster1::security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi       password    ci_readonly    no
....


== 疑難排解

如果您在使用此資料收集器時遇到問題、請嘗試下列事項：

[cols="2*"]
|===
| 問題： | 試用： 


| 嘗試建立 ONTAP REST 資料收集器時、會出現如下錯誤：
組態： 10.193.70.14 ： ONTAP REST API 於 10.193.70.14 不可用： 10.193.70.14 無法取得 /API/cluster ： 400 錯誤要求 | 這可能是因為使用了一種老舊的 ONTAP 陣列、例如 ONTAP 9.6 ）、而該陣列沒有 REST API 功能。ONTAP 9.14.1 是 ONTAP REST 收集器支援的最低 ONTAP 版本。在預先休息的 ONTAP 版本中、應會有「 400 不良要求」回應。

對於支援 REST 但非 9.14.1 或更新版本的 ONTAP 版本、您可能會看到下列訊息：
組態： 10.193.98.84 ： ONTAP REST API 於 10.193.98.84 不可用： 10.193.98.84 ： ONTAP REST API 於 10.193.98.84 提供： cheryl5-cluster 2 9.10.1 a3cb3247-3d3c-11ee-8ff3-005056b364a7 、但不是最低版本 9.14.1 。 
|===
如需其他資訊、請參閱 link:concept_requesting_support.html["支援"] 頁面或中的 link:reference_data_collector_support_matrix.html["資料收集器支援對照表"]。
